# Generated by Django 3.2.9 on 2021-11-25 16:30

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_features', '0004_auto_20211125_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
    ]
