# Generated by Django 3.2.9 on 2021-12-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_features', '0006_auto_20211129_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pud_date'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
