# Generated by Django 3.2.9 on 2021-12-05 19:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_features', '0008_auto_20211205_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipe_features.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'The amount must be more than zero.'), django.core.validators.MaxValueValidator(10000, 'The amount must be less than zero.')], verbose_name='quantity of ingredient'),
        ),
        migrations.DeleteModel(
            name='TagRecipe',
        ),
    ]
